# --- Concurrency & retries ---
max_concurrency = 8
max_retries = 2
retry_wait_time = 2   # seconds
timeout = 20          # seconds

# --- Friendlier UA (some sites block bots) ---
user_agent = "Mozilla/5.0 (compatible; Lychee/2.0; +https://github.com/lycheeverse/lychee)"

# --- Skip whole folders in the built site (optional) ---
exclude_path = [
  "./public/talks/**"
]

# --- Ignore known bot-hostile or irrelevant links (regex) ---
exclude = [
  "^https?://(www\\.)?reddit\\.com/submit.*",
  "^https?://news\\.ycombinator\\.com/submitlink.*",
  "^http://localhost(:\\d+)?/.*",
  "^file://.*",
  # Optional: add particularly flaky domains below
  "^https?://ember-fastboot\\.com/.*",
  "^https?://phaser\\.io/.*",
  "^https?://(www\\.)?webpagetest\\.org/.*"
]