# Site settings
title: Alex DiLiberto
baseurl: ""
url: "http://alexdiliberto.com"
firstname: Alex
lastname: DiLiberto
author: Alex DiLiberto


# Contact settings
username: alexdiliberto
twitter_username: alex_diliberto
facebook_username: diliberto.alex
email: hello@alexdiliberto.com
city: "Charlotte, NC, USA"


# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/


# Sass
sass:
  sass_dir: _sass
  style: :compressed


# Ruby Gems
gems:
  - jekyll-sitemap
  - jemoji


# Defaults
defaults:
  -
    scope:
      path: "" # empty string represents all files
    values:
      description: "Hi! I'm Alex DiLiberto. I'm a web developer living in Charlotte, NC and this is my personal site."
