# Site settings
title: Alex DiLiberto
baseurl: ""
url: "https://alexdiliberto.com"
firstname: Alex
lastname: DiLiberto
author: Alex DiLiberto


# Contact settings
username: alexdiliberto
twitter_username: alex_diliberto
facebook_username: diliberto.alex
email: hello@alexdiliberto.com
city: "Charlotte, NC, USA"


# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/


# Sass
sass:
  sass_dir: _sass
  style: :compressed


# Jekyll Plugins
plugins:
  - jekyll-sitemap
  - jemoji

# Exclude files and directories
exclude:
  - talks/**/node_modules
  - node_modules

# Defaults
defaults:
  -
    scope:
      path: "" # empty string represents all files
    values:
      description: "Hi! I'm Alex DiLiberto, software engineer and web developer living in Charlotte, NC and this is my personal site."
