name: Deploy Hugo to GitHub Pages

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# separate concurrency for branches/PRs so previews don't block each other
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        # using Hugo Modules, not submodules
        with:
          submodules: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true

      - name: Build /public
        run: |
          hugo --minify --gc --enableGitInfo

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          # PRs get a preview URL and pushes to `main` go straight to production
          preview: ${{ github.event_name == 'pull_request' }}
